In [78]:
import numpy as np

In [79]:
Variables =['Fe2O3_charge','C_charge','O2_blast','N2_offgas','Fe_product','CO_offgas','CO2_offgas','N2_blast']

In [98]:
a=np.array([[0,      0,     0,      0,       1,       0,       0,       0,       0],\
            [-0.699, 0,     0,      0,       1,       0,       0,       0,       0],\
            [-0.301, 0,    -1,      0,       0,   0.571,   0.727,       0,       0],\
            [0,     -1,     0,      0,       0,   0.429,   0.273,       0,       0],\
            [0,      0,     0,      -1,      0,       0,       0,       1,       0],\
            [0,      0,   3.3,      -1,      0,       0,       0,       0,       0],\
            [0,      1,     0,       0,      0,       0,       0,       0,       0],\
            [0,      0,     0,       0,  0.047,      -1,       0,       0,       0],\
            [5.169,  0, -1.352,  -1.463, 1.269,       5,  -3.836,  -8.844,  0.1099]])
a

array([[ 0.    ,  0.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [-0.699 ,  0.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [-0.301 ,  0.    , -1.    ,  0.    ,  0.    ,  0.571 ,  0.727 ,
         0.    ,  0.    ],
       [ 0.    , -1.    ,  0.    ,  0.    ,  0.    ,  0.429 ,  0.273 ,
         0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    , -1.    ,  0.    ,  0.    ,  0.    ,
         1.    ,  0.    ],
       [ 0.    ,  0.    ,  3.3   , -1.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [ 0.    ,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.047 , -1.    ,  0.    ,
         0.    ,  0.    ],
       [ 5.169 ,  0.    , -1.352 , -1.463 ,  1.269 ,  5.    , -3.836 ,
        -8.844 ,  0.1099]])

In [95]:
y = np.array([1000, 0, 0, 0, 0, 0, 400, 0, -400])
y

array([1000,    0,    0,    0,    0,    0,  400,    0, -400])

In [96]:
x = np.linalg.solve(a, y)
x

array([1.43061516e+03, 4.00000000e+02, 6.07729158e+02, 2.00550622e+03,
       1.00000000e+03, 4.70000000e+01, 1.39134432e+03, 2.00550622e+03,
       1.59515464e+05])