In [3]:
import numpy as np

In [55]:
variables =['Fe2O3_charge','C_charge','O2_blast','N2_offgas','Fe_product','CO_offgas','CO2_offgas','N2_blast']

In [56]:
a=np.array([[0,      0,     0,      0,        1,       0,       0,       0,       0],\
            [-0.699, 0,     0,      0,        1,       0,       0,       0,       0],\
            [-0.301, 0,    -1,      0,        0,       0,   0.571,   0.727,       0],\
            [0,     -1,     0,      0,        0,       1,   0.429,   0.273,       0],\
            [0,      0,     0,      -1,       0,       0,       0,       0,       1],\
            [0,      0,   3.3,      -1,       0,       0,       0,       0,       0],\
            [0,      1,     0,       0,       0,       0,       0,       0,       0],\
            [0,      0,     0,       0,   0.047,      -1,       0,       0,       0],\
            [5.169,  0, -1.352,  -1.463,  1.269,       5,  -3.836,  -8.844,  0.1099]])
a

array([[ 0.    ,  0.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [-0.699 ,  0.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [-0.301 ,  0.    , -1.    ,  0.    ,  0.    ,  0.    ,  0.571 ,
         0.727 ,  0.    ],
       [ 0.    , -1.    ,  0.    ,  0.    ,  0.    ,  1.    ,  0.429 ,
         0.273 ,  0.    ],
       [ 0.    ,  0.    ,  0.    , -1.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  1.    ],
       [ 0.    ,  0.    ,  3.3   , -1.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [ 0.    ,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.047 , -1.    ,  0.    ,
         0.    ,  0.    ],
       [ 5.169 ,  0.    , -1.352 , -1.463 ,  1.269 ,  5.    , -3.836 ,
        -8.844 ,  0.1099]])

In [57]:
y = np.array([1000, 0, 0, 0, 0, 0, 400, 0, -400])
y

array([1000,    0,    0,    0,    0,    0,  400,    0, -400])

In [58]:
x = np.linalg.solve(a, y)
x

array([1430.61516452,  400.        ,  291.70083268,  962.61274785,
       1000.        ,   47.        ,  381.01751772,  694.29847948,
        962.61274785])

In [71]:
results=[int(w) for w in x]
results

[1430, 400, 291, 962, 1000, 47, 381, 694, 962]

In [72]:
rdict = {a:b for (a,b) in zip(variables,results)}
from operator import itemgetter
rdict.get('Fe2O3_charge',-999)
Fe2O3_charge=rdict.get('Fe2O3_charge',-999)
for key in rdict:
    locals()[key] = rdict[key]

In [73]:
a = [1,2,4,5,12,16]
b = [5,2,8]

In [74]:
for i in range(len(a)):
    print(a[i],b[i])

1 5
2 2
4 8


IndexError: list index out of range

In [75]:
list(zip(a,b))

[(1, 5), (2, 2), (4, 8)]

In [63]:
for ai,bi in zip(a,b):
    print(ai,bi)

1 5
2 2
4 8
