In [3]:
import numpy as np

In [4]:
Variables =['Fe2O3_charge','C_charge','O2_blast','N2_offgas','Fe_product','CO_offgas','CO2_offgas','N2_blast']

In [14]:
a=np.array([[0,      0,     0,      0,        1,       0,       0,       0,       0],\
            [-0.699, 0,     0,      0,        1,       0,       0,       0,       0],\
            [-0.301, 0,    -1,      0,        0,       0,   0.571,   0.727,       0],\
            [0,     -1,     0,      0,        0,       1,   0.429,   0.273,       0],\
            [0,      0,     0,      -1,       0,       0,       0,       0,       1],\
            [0,      0,   3.3,      -1,       0,       0,       0,       0,       0],\
            [0,      1,     0,       0,       0,       0,       0,       0,       0],\
            [0,      0,     0,       0,   0.047,      -1,       0,       0,       0],\
            [5.169,  0, -1.352,  -1.463,  1.269,       5,  -3.836,  -8.844,  0.1099]])
a

array([[ 0.    ,  0.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [-0.699 ,  0.    ,  0.    ,  0.    ,  1.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [-0.301 ,  0.    , -1.    ,  0.    ,  0.    ,  0.    ,  0.571 ,
         0.727 ,  0.    ],
       [ 0.    , -1.    ,  0.    ,  0.    ,  0.    ,  1.    ,  0.429 ,
         0.273 ,  0.    ],
       [ 0.    ,  0.    ,  0.    , -1.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  1.    ],
       [ 0.    ,  0.    ,  3.3   , -1.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [ 0.    ,  1.    ,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  0.047 , -1.    ,  0.    ,
         0.    ,  0.    ],
       [ 5.169 ,  0.    , -1.352 , -1.463 ,  1.269 ,  5.    , -3.836 ,
        -8.844 ,  0.1099]])

In [15]:
y = np.array([1000, 0, 0, 0, 0, 0, 400, 0, -400])
y

array([1000,    0,    0,    0,    0,    0,  400,    0, -400])

In [16]:
x = np.linalg.solve(a, y)
x

array([1430.61516452,  400.        ,  291.70083268,  962.61274785,
       1000.        ,   47.        ,  381.01751772,  694.29847948,
        962.61274785])

In [22]:
results=[round(w,2) for w in x] 
results[0]

1430.62

In [29]:
rdict = {a:b for (a,b) in zip(Variables,results)}
from operator import itemgetter
rdict.get('Fe2O3_charge',-999)
Fe2O3_charge=rdict.get('Fe2O3_charge',-999)
for key in rdict:
    locals()[key] = rdict[key]